### ISSUE TITLE
News shared element transitions

### ISSUE THREAD

**Issue by Harsh2098** [delta/dalal-street-android#118]
Reverse shared element transition not working. (Going from NewsDetails Activity to Home/News Fragment)

**Comment by ranaaditya** [comment]
this issue has been resolved with [this](https://github.com/delta/dalal-street-android/commit/ce7cc50fc2ff6d67ea1ef9fd3964e64804b2f3b3) commit.

Thanks @satyamurti for this contribution :partying_face:
