### ISSUE TITLE
Fragment not resuming on backpress 

### ISSUE THREAD

**Issue by ranaaditya** [delta/dalal-street-android#160]
On calling **onBackPress()** fragment's lifecycle **restarts** instead of **resuming** !

**Comment by Harsh2098** [comment]
I think this is inherent to Jetpack's Android Navigation components. 

Ref: https://stackoverflow.com/questions/54581071/fragments-destroyed-recreated-with-jetpacks-android-navigation-components

**Comment by ranaaditya** [comment]
Yeah it is inherent feature of jetpack navigation component.
Consider as a feature for the app, as we don't have refresh feature so loading data for each backpress works for us.
