### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by avikumar15** [delta/dalal-street-android#189]
The admin panel needs to implement some more fields to make it consistent with web. Also currently we are not using a scrollview, so that has to be redesigned a bit.

Admin panel right now looks like 
![image](https://user-images.githubusercontent.com/41758822/108216067-0af7ba00-7158-11eb-8c30-0fa6b6218b05.png)

**Comment by satyamurti** [comment]
what other fields should be included

**Comment by avikumar15** [comment]
Add all these fields 
![image](https://user-images.githubusercontent.com/41758822/108218113-557a3600-715a-11eb-959f-063f4e2dcd5b.png)
I think a tab layout would look good, what say @ranaaditya ?

**Comment by ranaaditya** [comment]
> what other fields should be included

@satyamurti  please take a look of wen admin panel and implement all the left out features in app adin panel also.

**Comment by ranaaditya** [comment]
> Add all these fields
> ![image](https://user-images.githubusercontent.com/41758822/108218113-557a3600-715a-11eb-959f-063f4e2dcd5b.png)
> I think a tab layout would look good, what say @ranaaditya ?

@avikumar15 yeah **Tab Layout** will be a good option here to avoid mess in same fragment.

**Comment by satyamurti** [comment]
Ok got it 👍

**Comment by ranaaditya** [comment]
This issue has been resolved with [This](https://github.com/delta/dalal-street-android/commit/1f51fef944ce19765863a7034e5f2e4d42aa7631) commit.

Thanks @satyamurti for this wonderful contribution :partying_face: :partying_face:
